// 本文件由 ../Templates/Cpp/Error/Error.cpp.tpl 生成；请勿手改，改动请改模板后重跑 pumpall.py
#include "Error.h"
#include <map>

namespace QuantTrading
{
	std::map<unsigned int, std::string> Errors = {
		{ErrorNone, reinterpret_cast<const char*>(u8"正确")},
		{ErrorNetwork, reinterpret_cast<const char*>(u8"网络错误")},
		{ErrorIncorrectPassword, reinterpret_cast<const char*>(u8"密码错误")},
		{ErrorAccountNotExist, reinterpret_cast<const char*>(u8"账户不存在")},
		{ErrorPrimaryAccountNotExist, reinterpret_cast<const char*>(u8"主账户不存在")},
		{ErrorUserNotExist, reinterpret_cast<const char*>(u8"用户不存在")},
		{ErrorCapitalNotExist, reinterpret_cast<const char*>(u8"资金不存在")},
		{ErrorPrimaryCapitalNotExist, reinterpret_cast<const char*>(u8"主账户资金不存在")},
		{ErrorTradeOfferNotExist, reinterpret_cast<const char*>(u8"交易报盘不存在")},
		{ErrorExchangeNotExist, reinterpret_cast<const char*>(u8"交易所不存在")},
		{ErrorProductNotExist, reinterpret_cast<const char*>(u8"品种不存在")},
		{ErrorInstrumentNotExist, reinterpret_cast<const char*>(u8"合约不存在")},
		{ErrorOptionInstrumentNotExist, reinterpret_cast<const char*>(u8"期权合约不存在")},
		{ErrorUnderlyingInstrumentNotExist, reinterpret_cast<const char*>(u8"标的合约不存在")},
		{ErrorBaseCommissionNotExist, reinterpret_cast<const char*>(u8"基础费率不存在")},
		{ErrorCommissionGroupNotExist, reinterpret_cast<const char*>(u8"手续费组不存在")},
		{ErrorMarginGroupNotExist, reinterpret_cast<const char*>(u8"保证金组不存在")},
		{ErrorCurrencyRateNotExist, reinterpret_cast<const char*>(u8"币种汇率不存在")},
		{ErrorMarketDataNotExist, reinterpret_cast<const char*>(u8"行情数据不存在")},
		{ErrorUnderlyingMarketDataNotExist, reinterpret_cast<const char*>(u8"标的行情数据不存在")},
		{ErrorLastPriceNotExist, reinterpret_cast<const char*>(u8"最新价不存在")},
		{ErrorMaxSequenceNoNotExist, reinterpret_cast<const char*>(u8"最大委托序号不存在")},
		{ErrorOrderNotExist, reinterpret_cast<const char*>(u8"委托不存在")},
		{ErrorPositionNotExist, reinterpret_cast<const char*>(u8"持仓不存在")},
		{ErrorTradeGroupNotExist, reinterpret_cast<const char*>(u8"交易组不存在")},
		{ErrorTradeGroupItemNotExist, reinterpret_cast<const char*>(u8"交易组子项不存在")},
		{ErrorRiskGroupNotExist, reinterpret_cast<const char*>(u8"风控组不存在")},
		{ErrorRiskGroupItemNotExist, reinterpret_cast<const char*>(u8"风控组子项不存在")},
		{ErrorRiskNotExist, reinterpret_cast<const char*>(u8"风控不存在")},
		{ErrorAccountRiskNotExist, reinterpret_cast<const char*>(u8"账户风控不存在")},
		{ErrorOptionMarginParamNotExist, reinterpret_cast<const char*>(u8"期权保证金参数不存在")},
		{ErrorPrimaryOrderNotExist, reinterpret_cast<const char*>(u8"主账号委托不存在")},
		{ErrorSubOrderNotExist, reinterpret_cast<const char*>(u8"子账号委托不存在")},
		{ErrorSubAccountNotExist, reinterpret_cast<const char*>(u8"子账号不存在")},
		{ErrorBrokerNotExist, reinterpret_cast<const char*>(u8"经纪商不存在")},
		{ErrorPrimaryAccountAlreadyExist, reinterpret_cast<const char*>(u8"主账号已存在")},
		{ErrorAccountAlreadyExist, reinterpret_cast<const char*>(u8"账户已存在")},
		{ErrorCapitalAlreadyExist, reinterpret_cast<const char*>(u8"资金账号已存在")},
		{ErrorBaseCommissionAlreadyExist, reinterpret_cast<const char*>(u8"基础费率已存在")},
		{ErrorCommissionGroupAlreadyExist, reinterpret_cast<const char*>(u8"手续费组已存在")},
		{ErrorAdminUserAlreadyExist, reinterpret_cast<const char*>(u8"管理用户已存在")},
		{ErrorRiskUserAlreadyExist, reinterpret_cast<const char*>(u8"风控用户已存在")},
		{ErrorTradeOfferAlreadyExist, reinterpret_cast<const char*>(u8"交易报盘已存在")},
		{ErrorRiskAlreadyExist, reinterpret_cast<const char*>(u8"风控已存在")},
		{ErrorRiskRuleAlreadyExist, reinterpret_cast<const char*>(u8"风控规则已存在")},
		{ErrorRiskRuleItemAlreadyExist, reinterpret_cast<const char*>(u8"风控规则子项已存在")},
		{ErrorRiskTradeScopeAlreadyExist, reinterpret_cast<const char*>(u8"风控交易范围")},
		{ErrorAccountRiskAlreadyExist, reinterpret_cast<const char*>(u8"账户风控已存在")},
		{ErrorTradeGroupAlreadyExist, reinterpret_cast<const char*>(u8"交易组已存在")},
		{ErrorTradeGroupItemAlreadyExist, reinterpret_cast<const char*>(u8"交易组子项已存在")},
		{ErrorRiskGroupAlreadyExist, reinterpret_cast<const char*>(u8"风控组已存在")},
		{ErrorRiskGroupItemAlreadyExist, reinterpret_cast<const char*>(u8"风控组子项已存在")},
		{ErrorOptionMarginParamAlreadyExist, reinterpret_cast<const char*>(u8"保证金参数已存在")},
		{ErrorOrderAlreadyExist, reinterpret_cast<const char*>(u8"委托已存在")},
		{ErrorTradeAlreadyExist, reinterpret_cast<const char*>(u8"成交已存在")},
		{ErrorAccountAlreadyLogin, reinterpret_cast<const char*>(u8"账户已登录")},
		{ErrorSessionAlreadyLogin, reinterpret_cast<const char*>(u8"本连接已登录")},
		{ErrorAccountNotLogin, reinterpret_cast<const char*>(u8"账户未登录")},
		{ErrorPrimaryAccountNotLogin, reinterpret_cast<const char*>(u8"主账户未登录")},
		{ErrorUserNotLogin, reinterpret_cast<const char*>(u8"用户未登录")},
		{ErrorBrokerNotLogin, reinterpret_cast<const char*>(u8"经纪公司未登录")},
		{ErrorTradeOfferNotLogin, reinterpret_cast<const char*>(u8"交易报盘未登录")},
		{ErrorTradeOfferAlreadyLogin, reinterpret_cast<const char*>(u8"交易报盘已登录")},
		{ErrorSessionNotLogin, reinterpret_cast<const char*>(u8"本连接未登录")},
		{ErrorDuplicateOfferID, reinterpret_cast<const char*>(u8"重复的报盘代码")},
		{ErrorDuplicateClientOrderID, reinterpret_cast<const char*>(u8"重复的客户端委托编号")},
		{ErrorInvalidOrderPrice, reinterpret_cast<const char*>(u8"不合法的委托价格")},
		{ErrorInvalidOrderVolume, reinterpret_cast<const char*>(u8"不合法的委托数量")},
		{ErrorInvalidAccountClass, reinterpret_cast<const char*>(u8"不合法的账户类别")},
		{ErrorInvalidSecurityType, reinterpret_cast<const char*>(u8"不合法的证券类别")},
		{ErrorInvalidLastPrice, reinterpret_cast<const char*>(u8"不合法的最新价")},
		{ErrorInvalidSettlementPrice, reinterpret_cast<const char*>(u8"不合法的结算价")},
		{ErrorInvalidPreSettlementPrice, reinterpret_cast<const char*>(u8"不合法的昨结算价")},
		{ErrorInvalidClosePrice, reinterpret_cast<const char*>(u8"不合法的收盘价")},
		{ErrorInvalidPreClosePrice, reinterpret_cast<const char*>(u8"不合法的昨收盘价")},
		{ErrorInvalidOffsetFlag, reinterpret_cast<const char*>(u8"不合法的开平标志")},
		{ErrorInvalidDirection, reinterpret_cast<const char*>(u8"不合法的买卖方向")},
		{ErrorInvalidOrderPriceType, reinterpret_cast<const char*>(u8"不合法的委托价格类别")},
		{ErrorCapitalInsufficient, reinterpret_cast<const char*>(u8"资金不足")},
		{ErrorPositionInsufficient, reinterpret_cast<const char*>(u8"持仓不足")},
		{ErrorReqPackageParseFailed, reinterpret_cast<const char*>(u8"请求报文解析失败")},
		{ErrorInsertOrderFailed, reinterpret_cast<const char*>(u8"添加委托记录失败")},
		{ErrorAccountRiskCheckFailed, reinterpret_cast<const char*>(u8"账户风控检查失败")},
		{ErrorPriamaryAccountRiskCheckFailed, reinterpret_cast<const char*>(u8"主账户风控检查失败")},
		{ErrorAccountGroupRiskCheckFailed, reinterpret_cast<const char*>(u8"账户组风控检查失败")},
		{ErrorNoAuthorityToQueryAccount, reinterpret_cast<const char*>(u8"没有权限查询该账户")},
		{ErrorNoAuthorityToOperateAccount, reinterpret_cast<const char*>(u8"没有权限操作该账户")},
		{ErrorNoAuthorityToTradeThisMarket, reinterpret_cast<const char*>(u8"没有该市场交易权限")},
		{ErrorNoTradingTime, reinterpret_cast<const char*>(u8"非交易时间")},
		{ErrorAccountDeleted, reinterpret_cast<const char*>(u8"账号已删除")},
		{ErrorUserDeleted, reinterpret_cast<const char*>(u8"用户已删除")},
		{ErrorTradeOfferDeleted, reinterpret_cast<const char*>(u8"交易报盘已删除")},
		{ErrorPasswordChanged, reinterpret_cast<const char*>(u8"密码已修改")},
		{ErrorAccountForbidden, reinterpret_cast<const char*>(u8"账号已禁用")},
		{ErrorFinalOrderStatus, reinterpret_cast<const char*>(u8"委托已是最终状态")},
		{ErrorCurrOrderStatusNeedNotAudit, reinterpret_cast<const char*>(u8"当前委托状态不需要审核")},
		{ErrorCurrOrderStatusNeedNotRiskCheck, reinterpret_cast<const char*>(u8"当前委托状态不需要风控检查")},
		{ErrorTradingDayNotMatch, reinterpret_cast<const char*>(u8"交易日不匹配")},
		{ErrorMarketDataUnInitialized, reinterpret_cast<const char*>(u8"行情未初始化")},
		{ErrorPrimaryAccountUnInitialized, reinterpret_cast<const char*>(u8"主账号未初始化")},
		{ErrorOfferApiNotExist, reinterpret_cast<const char*>(u8"报盘API不存在")},
		{ErrorOfferSendFailed, reinterpret_cast<const char*>(u8"报盘发送失败")},
		{ErrorAuditReject, reinterpret_cast<const char*>(u8"审核拒绝")},
	};

	const char* GetErrorMessage(unsigned int errorId)
	{
		return Errors[errorId].c_str();
	}
}