cmake_minimum_required(VERSION 3.5)
SET(PROJECT_NAME "QuantTrading")
project(${PROJECT_NAME})

set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 20)
set(BUILD_TEST_PROJECT 1)
set(LibsPath "${CMAKE_SOURCE_DIR}/../Libs")

add_definitions(-DUNICODE -D_UNICODE)
message("CMAKE_BUILD_TYPE:" ${CMAKE_BUILD_TYPE})
message("CMAKE_SYSTEM_NAME:" ${CMAKE_SYSTEM_NAME})
message("CMAKE_CL_64:" ${CMAKE_CL_64})
IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
	#string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
	#string(REPLACE "/MDd" "/MTd" CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
	add_definitions("-DWINDOWS")
	add_definitions("-D_CRT_SECURE_NO_WARNINGS")
	add_definitions("-D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING")
ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Linux")
	IF(CMAKE_BUILD_TYPE MATCHES "Debug")
		#list(APPEND CMAKE_CXX_FLAGS "-fsanitize=address")
	ENDIF()
	add_definitions("-DLINUX")
ENDIF()
message("CMAKE_CXX_FLAGS:" ${CMAKE_CXX_FLAGS})
message("CMAKE_CXX_FLAGS_RELEASE:" ${CMAKE_CXX_FLAGS_RELEASE})
message("CMAKE_CXX_FLAGS_DEBUG:" ${CMAKE_CXX_FLAGS_DEBUG})

macro(add_package name dir)
	include_directories(${dir})
	set(SUFFIXES  "*.cpp" "*.c" "*.cu")
	set(package_files "")
    foreach(suffix ${SUFFIXES})
        file(GLOB_RECURSE temp_files ${dir}/${suffix})
        list(APPEND package_files ${temp_files})
    endforeach()
    source_group(${ARGV0} FILES ${package_files})
    set(all_file ${all_file} ${package_files})
endmacro(add_package)

macro(add_res_package name dir)
	include_directories(${dir})
	file(GLOB_RECURSE res ${dir}/*)
	source_group(${ARGV0} FILES ${res})
	set(all_file ${all_file} ${res})
endmacro(add_res_package)


set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Linux")
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/lib)
ENDIF()
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/lib)
include_directories(${CMAKE_SOURCE_DIR}/include)
link_directories(${CMAKE_SOURCE_DIR}/lib)

include_directories(${CMAKE_SOURCE_DIR}/../Libs/PersonalLib/include)
link_directories(${CMAKE_SOURCE_DIR}/../Libs/PersonalLib/win64)

string(TIMESTAMP BUILD_TIMESTAMP "%Y%m%d-%H%M%S")
message("Build timestamp is ${BUILD_TIMESTAMP}")
configure_file(
    "${CMAKE_SOURCE_DIR}/Source/Version/BuildTime.cpp.in"
	"${CMAKE_SOURCE_DIR}/Source/Version/BuildTime.cpp"
    @ONLY
)

add_subdirectory(Api)
add_subdirectory(Target)
add_subdirectory(Test)
