#include "Error.h"
#include <map>


std::map<unsigned int, std::string> g_Errors = {
	{ErrorNone, (const char*)u8"正确"},
	{ErrorNetwork, (const char*)u8"网络错误"},
	{ErrorIncorrectPassword, (const char*)u8"密码错误"},
	{ErrorAccountNotExist, (const char*)u8"账户不存在"},
	{ErrorPrimaryAccountNotExist, (const char*)u8"主账户不存在"},
	{ErrorRiskUserNotExist, (const char*)u8"风控用户不存在"},
	{ErrorCapitalNotExist, (const char*)u8"资金不存在"},
	{ErrorPrimaryCapitalNotExist, (const char*)u8"主账户资金不存在"},
	{ErrorTradeOfferNotExist, (const char*)u8"交易报盘不存在"},
	{ErrorExchangeNotExist, (const char*)u8"交易所不存在"},
	{ErrorProductNotExist, (const char*)u8"品种不存在"},
	{ErrorInstrumentNotExist, (const char*)u8"合约不存在"},
	{ErrorOptionInstrumentNotExist, (const char*)u8"期权合约不存在"},
	{ErrorUnderlyingInstrumentNotExist, (const char*)u8"标的合约不存在"},
	{ErrorBaseCommissionNotExist, (const char*)u8"基础费率不存在"},
	{ErrorCommissionGroupNotExist, (const char*)u8"手续费组不存在"},
	{ErrorMarginGroupNotExist, (const char*)u8"保证金组不存在"},
	{ErrorCurrencyRateNotExist, (const char*)u8"币种汇率不存在"},
	{ErrorMarketDataNotExist, (const char*)u8"行情数据不存在"},
	{ErrorUnderlyingMarketDataNotExist, (const char*)u8"标的行情数据不存在"},
	{ErrorLastPriceNotExist, (const char*)u8"最新价不存在"},
	{ErrorMaxSequenceNoNotExist, (const char*)u8"最大委托序号不存在"},
	{ErrorOrderNotExist, (const char*)u8"委托不存在"},
	{ErrorPositionNotExist, (const char*)u8"持仓不存在"},
	{ErrorTradeGroupNotExist, (const char*)u8"交易组不存在"},
	{ErrorTradeGroupItemNotExist, (const char*)u8"交易组子项不存在"},
	{ErrorRiskGroupNotExist, (const char*)u8"风控组不存在"},
	{ErrorRiskGroupItemNotExist, (const char*)u8"风控组子项不存在"},
	{ErrorAdminUserNotExist, (const char*)u8"管理用户不存在"},
	{ErrorRiskNotExist, (const char*)u8"风控不存在"},
	{ErrorAccountRiskNotExist, (const char*)u8"账户风控不存在"},
	{ErrorOptionMarginParamNotExist, (const char*)u8"期权保证金参数不存在"},
	{ErrorPrimaryOrderNotExist, (const char*)u8"主账号委托不存在"},
	{ErrorSubOrderNotExist, (const char*)u8"子账号委托不存在"},
	{ErrorSubAccountNotExist, (const char*)u8"子账号不存在"},
	{ErrorBrokerNotExist, (const char*)u8"经纪商不存在"},
	{ErrorPrimaryAccountAlreadyExist, (const char*)u8"主账号已存在"},
	{ErrorAccountAlreadyExist, (const char*)u8"账户已存在"},
	{ErrorCapitalAlreadyExist, (const char*)u8"资金账号已存在"},
	{ErrorBaseCommissionAlreadyExist, (const char*)u8"基础费率已存在"},
	{ErrorCommissionGroupAlreadyExist, (const char*)u8"手续费组已存在"},
	{ErrorAdminUserAlreadyExist, (const char*)u8"管理用户已存在"},
	{ErrorRiskUserAlreadyExist, (const char*)u8"风控用户已存在"},
	{ErrorTradeOfferAlreadyExist, (const char*)u8"交易报盘已存在"},
	{ErrorRiskAlreadyExist, (const char*)u8"风控已存在"},
	{ErrorRiskRuleAlreadyExist, (const char*)u8"风控规则已存在"},
	{ErrorRiskRuleItemAlreadyExist, (const char*)u8"风控规则子项已存在"},
	{ErrorRiskTradeScopeAlreadyExist, (const char*)u8"风控交易范围"},
	{ErrorAccountRiskAlreadyExist, (const char*)u8"账户风控已存在"},
	{ErrorTradeGroupAlreadyExist, (const char*)u8"交易组已存在"},
	{ErrorTradeGroupItemAlreadyExist, (const char*)u8"交易组子项已存在"},
	{ErrorRiskGroupAlreadyExist, (const char*)u8"风控组已存在"},
	{ErrorRiskGroupItemAlreadyExist, (const char*)u8"风控组子项已存在"},
	{ErrorOptionMarginParamAlreadyExist, (const char*)u8"保证金参数已存在"},
	{ErrorOrderAlreadyExist, (const char*)u8"委托已存在"},
	{ErrorTradeAlreadyExist, (const char*)u8"成交已存在"},
	{ErrorAccountAlreadyLogin, (const char*)u8"账户已登录"},
	{ErrorSessionAlreadyLogin, (const char*)u8"本链接已登录"},
	{ErrorAccountNotLogin, (const char*)u8"账户未登录"},
	{ErrorPrimaryAccountNotLogin, (const char*)u8"主账户未登录"},
	{ErrorUserNotLogin, (const char*)u8"用户未登录"},
	{ErrorTradeOfferNotLogin, (const char*)u8"交易报盘未登录"},
	{ErrorTradeOfferAlreadyLogin, (const char*)u8"交易报盘已登录"},
	{ErrorDuplicateOfferID, (const char*)u8"重复的报盘代码"},
	{ErrorDuplicateClientOrderID, (const char*)u8"重复的客户端委托编号"},
	{ErrorInvalidOrderPrice, (const char*)u8"不合法的委托价格"},
	{ErrorInvalidOrderVolume, (const char*)u8"不合法的委托数量"},
	{ErrorInvalidAccountClass, (const char*)u8"不合法的账户类别"},
	{ErrorInvalidSecurityType, (const char*)u8"不合法的证券类别"},
	{ErrorInvalidLastPrice, (const char*)u8"不合法的最新价"},
	{ErrorInvalidSettlementPrice, (const char*)u8"不合法的结算价"},
	{ErrorInvalidPreSettlementPrice, (const char*)u8"不合法的昨结算价"},
	{ErrorInvalidClosePrice, (const char*)u8"不合法的收盘价"},
	{ErrorInvalidPreClosePrice, (const char*)u8"不合法的昨收盘价"},
	{ErrorInvalidOffsetFlag, (const char*)u8"不合法的开平标志"},
	{ErrorInvalidDirection, (const char*)u8"不合法的买卖方向"},
	{ErrorInvalidOrderPriceType, (const char*)u8"不合法的委托价格类别"},
	{ErrorCapitalInsufficient, (const char*)u8"资金不足"},
	{ErrorPositionInsufficient, (const char*)u8"持仓不足"},
	{ErrorReqPackageParseFailed, (const char*)u8"请求报文解析失败"},
	{ErrorInsertOrderFailed, (const char*)u8"添加委托记录失败"},
	{ErrorAccountRiskCheckFailed, (const char*)u8"账户风控检查失败"},
	{ErrorPriamaryAccountRiskCheckFailed, (const char*)u8"主账户风控检查失败"},
	{ErrorAccountGroupRiskCheckFailed, (const char*)u8"账户组风控检查失败"},
	{ErrorNoAuthorityToQueryAccount, (const char*)u8"没有权限查询该账户"},
	{ErrorNoAuthorityToOperateAccount, (const char*)u8"没有权限操作该账户"},
	{ErrorNoAuthorityToTradeThisMarket, (const char*)u8"没有该市场交易权限"},
	{ErrorNoTradingTime, (const char*)u8"非交易时间"},
	{ErrorAccountDeleted, (const char*)u8"账号已删除"},
	{ErrorUserDeleted, (const char*)u8"用户已删除"},
	{ErrorTradeOfferDeleted, (const char*)u8"交易报盘已删除"},
	{ErrorPasswordChanged, (const char*)u8"密码已修改"},
	{ErrorAccountForbidden, (const char*)u8"账号已禁用"},
	{ErrorFinalOrderStatus, (const char*)u8"委托已是最终状态"},
	{ErrorCurrOrderStatusNeedNotAudit, (const char*)u8"当前委托状态不需要审核"},
	{ErrorCurrOrderStatusNeedNotRiskCheck, (const char*)u8"当前委托状态不需要风控检查"},
	{ErrorTradingDayNotMatch, (const char*)u8"交易日不匹配"},
	{ErrorMarketDataUnInitialized, (const char*)u8"行情未初始化"},
	{ErrorPrimaryAccountUnInitialized, (const char*)u8"主账号未初始化"},
	{ErrorOfferApiNotExist, (const char*)u8"报盘API不存在"},
	{ErrorOfferSendFailed, (const char*)u8"报盘发送失败"},
	{ErrorAuditReject, (const char*)u8"审核拒绝"},
};

const char* GetErrorMessage(unsigned int errorID)
{
	return g_Errors[errorID].c_str();
}
