
CREATE TABLE IF NOT EXISTS t_TradingDay (
  PK varchar,  -- '主键'
  CurrTradingDay varchar,  -- '当前交易日'
  PreTradingDay varchar,  -- '昨交易日'
  PRIMARY KEY(PK)
);  -- '交易日'


CREATE TABLE IF NOT EXISTS t_Exchange (
  ExchangeID varchar,  -- '交易所代码'
  ExchangeName varchar,  -- '交易所名称'
  PRIMARY KEY(ExchangeID)
);  -- '交易所'


CREATE TABLE IF NOT EXISTS t_Product (
  ExchangeID varchar,  -- '交易所代码'
  ProductID varchar,  -- '品种代码'
  ProductName varchar,  -- '品种名称'
  SecurityType int,  -- '证券类别'
  VolumeMultiple int,  -- '合约乘数'
  PriceTick double,  -- '最小变动价位'
  MaxMarketOrderVolume bigint,  -- '市价最大下单量'
  MinMarketOrderVolume bigint,  -- '市价最小下单量'
  MaxLimitOrderVolume bigint,  -- '限价最大下单量'
  MinLimitOrderVolume bigint,  -- '限价最小下单量'
  SessionName varchar,  -- '交易节名称'
  PRIMARY KEY(ExchangeID, ProductID)
);  -- '品种表'


CREATE TABLE IF NOT EXISTS t_Instrument (
  TradingDay varchar,  -- '交易日'
  ExchangeID varchar,  -- '交易所代码'
  InstrumentID varchar,  -- '合约代码'
  ExchangeInstID varchar,  -- '交易所合约代码'
  InstrumentName varchar,  -- '合约名称'
  ProductID varchar,  -- '品种代码'
  SecurityType int,  -- '证券类别'
  SecurityDetailType int,  -- '证券细分类别'
  VolumeMultiple int,  -- '合约乘数'
  PriceTick double,  -- '最小变动价位'
  MaxMarketOrderVolume bigint,  -- '市价最大下单量'
  MinMarketOrderVolume bigint,  -- '市价最小下单量'
  MaxLimitOrderVolume bigint,  -- '限价最大下单量'
  MinLimitOrderVolume bigint,  -- '限价最小下单量'
  SessionName varchar,  -- '交易节名称'
  PRIMARY KEY(ExchangeID, InstrumentID)
);  -- '合约'


CREATE TABLE IF NOT EXISTS t_PrimaryAccount (
  TradingDay varchar,  -- '交易日'
  PrimaryAccountID varchar,  -- '主账户代码'
  PrimaryAccountName varchar,  -- '主账户名称'
  AccountClass int,  -- '账户类别'
  BrokerPassword varchar,  -- '经纪公司密码'
  OfferID int,  -- '报盘代码'
  IsAllowLogin int,  -- '是否允许登陆'
  IsSimulateAccount int,  -- '是否模拟账号'
  LoginStatus int,  -- '登录状态'
  InitStatus int,  -- '初始化状态'
  PRIMARY KEY(PrimaryAccountID)
);  -- '主账户'
  CREATE INDEX OfferID ON t_PrimaryAccount();


CREATE TABLE IF NOT EXISTS t_Account (
  TradingDay varchar,  -- '交易日'
  AccountID varchar,  -- '账户代码'
  AccountName varchar,  -- '账户名称'
  AccountType int,  -- '账户类型'
  AccountStatus int,  -- '账户状态'
  Password varchar,  -- '密码'
  TradeGroupID int,  -- '交易组代码'
  RiskGroupID int,  -- '交易组代码'
  CommissionGroupID int,  -- '交易组代码'
  PRIMARY KEY(AccountID)
);  -- '账户'


CREATE TABLE IF NOT EXISTS t_Capital (
  TradingDay varchar,  -- '交易日'
  AccountID varchar,  -- '账户代码'
  AccountType int,  -- '账户类型'
  Asset double,  -- '总资产'
  PreAsset double,  -- '上日总资产'
  CashAsset double,  -- '现金资产'
  PreCashAsset double,  -- '上日现金资产'
  Available double,  -- '可用资金'
  CashIn double,  -- '现金收入'
  CashOut double,  -- '现金支出'
  Margin double,  -- '保证金'
  Commission double,  -- '手续费'
  StampTax double,  -- '印花税'
  TransferFee double,  -- '过户费'
  FrozenCash double,  -- '冻结资金'
  FrozenMargin double,  -- '冻结保证金'
  FrozenCommission double,  -- '冻结手续费'
  FrozenStampTax double,  -- '冻结印花税'
  FrozenTransferFee double,  -- '冻结过户费'
  MarketValue double,  -- '市值'
  TotalProfit double,  -- '总盈亏'
  TodayProfit double,  -- '当日盈亏'
  Deposit double,  -- '入金'
  Withdraw double,  -- '出金'
  PRIMARY KEY(AccountID)
);  -- '资金'


CREATE TABLE IF NOT EXISTS t_Position (
  TradingDay varchar,  -- '交易日'
  AccountID varchar,  -- '账户代码'
  AccountType int,  -- '账户类型'
  ExchangeID varchar,  -- '交易所代码'
  InstrumentID varchar,  -- '合约代码'
  SecurityType int,  -- '证券类别'
  PosiDirection int,  -- '持仓方向'
  TotalPosition bigint,  -- '持仓数量'
  PositionFrozen bigint,  -- '冻结持仓'
  TodayPosition bigint,  -- '今日持仓'
  CashIn double,  -- '现金收入'
  CashOut double,  -- '现金支出'
  Margin double,  -- '保证金'
  Commission double,  -- '手续费'
  StampTax double,  -- '印花税'
  TransferFee double,  -- '过户费'
  FrozenCash double,  -- '冻结资金'
  FrozenMargin double,  -- '冻结保证金'
  FrozenCommission double,  -- '冻结手续费'
  FrozenStampTax double,  -- '冻结印花税'
  FrozenTransferFee double,  -- '冻结过户费'
  MarketValue double,  -- '市值'
  VolumeMultiple int,  -- '合约乘数'
  CloseProfit double,  -- '逐日平仓盈亏'
  CloseProfitFloat double,  -- '逐笔平仓盈亏'
  PositionProfit double,  -- '逐日持仓盈亏'
  PositionProfitFloat double,  -- '逐笔持仓盈亏'
  LastPrice double,  -- '最新价'
  PrePrice double,  -- '昨收盘价或昨结算价'
  PRIMARY KEY(TradingDay, AccountID, ExchangeID, InstrumentID, PosiDirection)
);  -- '持仓'
  CREATE INDEX Account ON t_Position();


CREATE TABLE IF NOT EXISTS t_Order (
  TradingDay varchar,  -- '交易日'
  AccountID varchar,  -- '账户代码'
  PrimaryAccountID varchar,  -- '主账户代码'
  AccountType int,  -- '账户类型'
  ExchangeID varchar,  -- '交易所代码'
  InstrumentID varchar,  -- '合约代码'
  SecurityType int,  -- '证券类别'
  OrderID int,  -- '委托编号'
  OrderSysID varchar,  -- '系统委托编号'
  Direction int,  -- '买卖方向'
  OffsetFlag int,  -- '开平标志'
  OrderPriceType int,  -- '委托价格类型'
  Price double,  -- '委托价格'
  Volume bigint,  -- '委托数量'
  VolumeTotal bigint,  -- '剩余数量'
  VolumeTraded bigint,  -- '成交数量'
  VolumeMultiple int,  -- '合约乘数'
  OrderStatus int,  -- '委托状态'
  OrderDate varchar,  -- '委托日期'
  OrderTime varchar,  -- '委托时间'
  CancelDate varchar,  -- '撤单日期'
  CancelTime varchar,  -- '撤单时间'
  SessionID bigint,  -- '会话编号'
  ClientOrderID int,  -- '客户端委托编号'
  RequestID int,  -- '客户端请求编号'
  OfferID int,  -- '报盘代码'
  TradeGroupID int,  -- '交易组代码'
  RiskGroupID int,  -- '交易组代码'
  CommissionGroupID int,  -- '交易组代码'
  FrozenCash double,  -- '冻结资金'
  FrozenMargin double,  -- '冻结保证金'
  FrozenCommission double,  -- '冻结手续费'
  FrozenStampTax double,  -- '冻结印花税'
  FrozenTransferFee double,  -- '冻结过户费'
  RebuildMark int,  -- '重建标志'
  IsForceClose int,  -- '是否强平单'
  UNIQUE (TradingDay, AccountID, ExchangeID, InstrumentID, SessionID, ClientOrderID),
  PRIMARY KEY(TradingDay, AccountID, ExchangeID, InstrumentID, OrderID)
);  -- '委托'


CREATE TABLE IF NOT EXISTS t_Trade (
  TradingDay varchar,  -- '交易日'
  AccountID varchar,  -- '账户代码'
  PrimaryAccountID varchar,  -- '主账户代码'
  AccountType int,  -- '账户类型'
  ExchangeID varchar,  -- '交易所代码'
  InstrumentID varchar,  -- '合约代码'
  SecurityType int,  -- '证券类别'
  OrderID int,  -- '委托编号'
  OrderSysID varchar,  -- '系统委托编号'
  TradeID varchar,  -- '成交编号'
  Direction int,  -- '买卖方向'
  OffsetFlag int,  -- '开平标志'
  Price double,  -- '委托价格'
  Volume bigint,  -- '委托数量'
  VolumeMultiple int,  -- '合约乘数'
  TradeAmount double,  -- '成交金额'
  Commission double,  -- '手续费'
  StampTax double,  -- '印花税'
  TransferFee double,  -- '过户费'
  TradeDate varchar,  -- '成交日期'
  TradeTime varchar,  -- '成交时间'
  PRIMARY KEY(TradingDay, ExchangeID, TradeID, Direction)
);  -- '成交'


CREATE TABLE IF NOT EXISTS t_DepthMarketData (
  TradingDay varchar,  -- '交易日'
  ExchangeID varchar,  -- '交易所代码'
  InstrumentID varchar,  -- '合约代码'
  LastPrice double,  -- '最新价'
  PreSettlementPrice double,  -- '昨结算价'
  PreClosePrice double,  -- '昨收盘价'
  PreOpenInterest bigint,  -- '上日持仓量'
  OpenPrice double,  -- '开盘价'
  HighestPrice double,  -- '最高价'
  LowestPrice double,  -- '最低价'
  ClosePrice double,  -- '收盘价'
  CurrVolume bigint,  -- '当前数量'
  Volume bigint,  -- '委托数量'
  CurrTurnover double,  -- '当前成交金额'
  Turnover double,  -- '成交金额'
  OpenInterest bigint,  -- '持仓量'
  SettlementPrice double,  -- '结算价'
  UpperLimitPrice double,  -- '涨停板价'
  LowerLimitPrice double,  -- '跌停板价'
  AveragePrice double,  -- '当日均价'
  UpdateTs bigint,  -- '更新时间戳'
  AskPrice1 double,  -- '申卖价一'
  AskPrice2 double,  -- '申卖价二'
  AskPrice3 double,  -- '申卖价三'
  AskPrice4 double,  -- '申卖价四'
  AskPrice5 double,  -- '申卖价五'
  AskPrice6 double,  -- '申卖价六'
  AskPrice7 double,  -- '申卖价七'
  AskPrice8 double,  -- '申卖价八'
  AskPrice9 double,  -- '申卖价九'
  AskPrice10 double,  -- '申卖价十'
  AskVolume1 bigint,  -- '申卖量一'
  AskVolume2 bigint,  -- '申卖量二'
  AskVolume3 bigint,  -- '申卖量三'
  AskVolume4 bigint,  -- '申卖量四'
  AskVolume5 bigint,  -- '申卖量五'
  AskVolume6 bigint,  -- '申卖量六'
  AskVolume7 bigint,  -- '申卖量七'
  AskVolume8 bigint,  -- '申卖量八'
  AskVolume9 bigint,  -- '申卖量九'
  AskVolume10 bigint,  -- '申卖量十'
  BidPrice1 double,  -- '申买价一'
  BidPrice2 double,  -- '申买价二'
  BidPrice3 double,  -- '申买价三'
  BidPrice4 double,  -- '申买价四'
  BidPrice5 double,  -- '申买价五'
  BidPrice6 double,  -- '申买价六'
  BidPrice7 double,  -- '申买价七'
  BidPrice8 double,  -- '申买价八'
  BidPrice9 double,  -- '申买价九'
  BidPrice10 double,  -- '申买价十'
  BidVolume1 bigint,  -- '申买量一'
  BidVolume2 bigint,  -- '申买量二'
  BidVolume3 bigint,  -- '申买量三'
  BidVolume4 bigint,  -- '申买量四'
  BidVolume5 bigint,  -- '申买量五'
  BidVolume6 bigint,  -- '申买量六'
  BidVolume7 bigint,  -- '申买量七'
  BidVolume8 bigint,  -- '申买量八'
  BidVolume9 bigint,  -- '申买量九'
  BidVolume10 bigint,  -- '申买量十'
  PRIMARY KEY(TradingDay, ExchangeID, InstrumentID)
);  -- '深度行情'



