DROP TABLE IF EXISTS t_TradingDay;
DROP TABLE IF EXISTS t_Exchange;
DROP TABLE IF EXISTS t_Product;
DROP INDEX HotInstrumentTradingDay;
DROP TABLE IF EXISTS t_HotInstrument;
DROP INDEX InstrumentExchangeID;
DROP TABLE IF EXISTS t_Instrument;
DROP TABLE IF EXISTS t_DepthMarketData;
DROP TABLE IF EXISTS t_BarMarketData;
DROP TABLE IF EXISTS t_MdSubscribe;
DROP TABLE IF EXISTS t_MdUser;
DROP INDEX MdUserLoginSessionMdUserID;
DROP TABLE IF EXISTS t_MdUserLoginSession;
DROP INDEX PrimaryAccountOfferID;
DROP TABLE IF EXISTS t_PrimaryAccount;
DROP TABLE IF EXISTS t_Account;
DROP INDEX CapitalTradingDay;
DROP TABLE IF EXISTS t_Capital;
DROP INDEX PositionAccount;
DROP INDEX PositionTradingDay;
DROP TABLE IF EXISTS t_Position;
DROP INDEX PositionDetailTradeMatch;
DROP INDEX PositionDetailTradingDay;
DROP TABLE IF EXISTS t_PositionDetail;
DROP INDEX OrderAccountID;
DROP TABLE IF EXISTS t_Order;
DROP INDEX TradeAccountID;
DROP TABLE IF EXISTS t_Trade;
DROP INDEX AccountLoginSessionAccountID;
DROP TABLE IF EXISTS t_AccountLoginSession;
