#pragma once
#include "DB.h"
#include "duckdb.hpp"
#include <string>
#include <list>


class DuckDB : public DB
{
public:
	DuckDB(const std::string& dbName);
	~DuckDB();
	virtual bool Connect() override;
	virtual void DisConnect() override;
	virtual void InitDB() override;
	virtual void CreateTables() override;
	virtual void DropTables() override;
	virtual void TruncateTables() override;
	virtual void TruncateSessionTables() override;
	
	bool Exec(const char* sql) const;
	virtual void CreateTradingDay() override;
	virtual void DropTradingDay() override;
	virtual void InsertTradingDay(mdb::TradingDay* record) override;
	virtual void BatchInsertTradingDay(std::list<mdb::TradingDay*>* records) override;
	virtual void DeleteTradingDay(mdb::TradingDay* record) override;
	virtual void UpdateTradingDay(mdb::TradingDay* record) override;
	virtual void SelectTradingDay(std::list<mdb::TradingDay*>& records) override;
	virtual void TruncateTradingDay() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::TradingDay*>& records);
	
	virtual void CreateExchange() override;
	virtual void DropExchange() override;
	virtual void InsertExchange(mdb::Exchange* record) override;
	virtual void BatchInsertExchange(std::list<mdb::Exchange*>* records) override;
	virtual void DeleteExchange(mdb::Exchange* record) override;
	virtual void UpdateExchange(mdb::Exchange* record) override;
	virtual void SelectExchange(std::list<mdb::Exchange*>& records) override;
	virtual void TruncateExchange() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Exchange*>& records);
	
	virtual void CreateProduct() override;
	virtual void DropProduct() override;
	virtual void InsertProduct(mdb::Product* record) override;
	virtual void BatchInsertProduct(std::list<mdb::Product*>* records) override;
	virtual void DeleteProduct(mdb::Product* record) override;
	virtual void UpdateProduct(mdb::Product* record) override;
	virtual void SelectProduct(std::list<mdb::Product*>& records) override;
	virtual void TruncateProduct() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Product*>& records);
	
	virtual void CreateHotInstrument() override;
	virtual void DropHotInstrument() override;
	virtual void InsertHotInstrument(mdb::HotInstrument* record) override;
	virtual void BatchInsertHotInstrument(std::list<mdb::HotInstrument*>* records) override;
	virtual void DeleteHotInstrument(mdb::HotInstrument* record) override;
	virtual void DeleteHotInstrumentByTradingDayIndex(mdb::HotInstrument* record) override;
	virtual void UpdateHotInstrument(mdb::HotInstrument* record) override;
	virtual void SelectHotInstrument(std::list<mdb::HotInstrument*>& records) override;
	virtual void TruncateHotInstrument() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::HotInstrument*>& records);
	
	virtual void CreateInstrument() override;
	virtual void DropInstrument() override;
	virtual void InsertInstrument(mdb::Instrument* record) override;
	virtual void BatchInsertInstrument(std::list<mdb::Instrument*>* records) override;
	virtual void DeleteInstrument(mdb::Instrument* record) override;
	virtual void UpdateInstrument(mdb::Instrument* record) override;
	virtual void SelectInstrument(std::list<mdb::Instrument*>& records) override;
	virtual void TruncateInstrument() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Instrument*>& records);
	
	virtual void CreatePrimaryAccount() override;
	virtual void DropPrimaryAccount() override;
	virtual void InsertPrimaryAccount(mdb::PrimaryAccount* record) override;
	virtual void BatchInsertPrimaryAccount(std::list<mdb::PrimaryAccount*>* records) override;
	virtual void DeletePrimaryAccount(mdb::PrimaryAccount* record) override;
	virtual void DeletePrimaryAccountByOfferIDIndex(mdb::PrimaryAccount* record) override;
	virtual void UpdatePrimaryAccount(mdb::PrimaryAccount* record) override;
	virtual void SelectPrimaryAccount(std::list<mdb::PrimaryAccount*>& records) override;
	virtual void TruncatePrimaryAccount() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::PrimaryAccount*>& records);
	
	virtual void CreateAccount() override;
	virtual void DropAccount() override;
	virtual void InsertAccount(mdb::Account* record) override;
	virtual void BatchInsertAccount(std::list<mdb::Account*>* records) override;
	virtual void DeleteAccount(mdb::Account* record) override;
	virtual void UpdateAccount(mdb::Account* record) override;
	virtual void SelectAccount(std::list<mdb::Account*>& records) override;
	virtual void TruncateAccount() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Account*>& records);
	
	virtual void CreateCapital() override;
	virtual void DropCapital() override;
	virtual void InsertCapital(mdb::Capital* record) override;
	virtual void BatchInsertCapital(std::list<mdb::Capital*>* records) override;
	virtual void DeleteCapital(mdb::Capital* record) override;
	virtual void DeleteCapitalByTradingDayIndex(mdb::Capital* record) override;
	virtual void UpdateCapital(mdb::Capital* record) override;
	virtual void SelectCapital(std::list<mdb::Capital*>& records) override;
	virtual void TruncateCapital() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Capital*>& records);
	
	virtual void CreatePosition() override;
	virtual void DropPosition() override;
	virtual void InsertPosition(mdb::Position* record) override;
	virtual void BatchInsertPosition(std::list<mdb::Position*>* records) override;
	virtual void DeletePosition(mdb::Position* record) override;
	virtual void DeletePositionByAccountIndex(mdb::Position* record) override;
	virtual void DeletePositionByTradingDayIndex(mdb::Position* record) override;
	virtual void UpdatePosition(mdb::Position* record) override;
	virtual void SelectPosition(std::list<mdb::Position*>& records) override;
	virtual void TruncatePosition() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Position*>& records);
	
	virtual void CreatePositionDetail() override;
	virtual void DropPositionDetail() override;
	virtual void InsertPositionDetail(mdb::PositionDetail* record) override;
	virtual void BatchInsertPositionDetail(std::list<mdb::PositionDetail*>* records) override;
	virtual void DeletePositionDetail(mdb::PositionDetail* record) override;
	virtual void DeletePositionDetailByTradeMatchIndex(mdb::PositionDetail* record) override;
	virtual void DeletePositionDetailByTradingDayIndex(mdb::PositionDetail* record) override;
	virtual void UpdatePositionDetail(mdb::PositionDetail* record) override;
	virtual void SelectPositionDetail(std::list<mdb::PositionDetail*>& records) override;
	virtual void TruncatePositionDetail() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::PositionDetail*>& records);
	
	virtual void CreateOrder() override;
	virtual void DropOrder() override;
	virtual void InsertOrder(mdb::Order* record) override;
	virtual void BatchInsertOrder(std::list<mdb::Order*>* records) override;
	virtual void DeleteOrder(mdb::Order* record) override;
	virtual void UpdateOrder(mdb::Order* record) override;
	virtual void SelectOrder(std::list<mdb::Order*>& records) override;
	virtual void TruncateOrder() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Order*>& records);
	
	virtual void CreateTrade() override;
	virtual void DropTrade() override;
	virtual void InsertTrade(mdb::Trade* record) override;
	virtual void BatchInsertTrade(std::list<mdb::Trade*>* records) override;
	virtual void DeleteTrade(mdb::Trade* record) override;
	virtual void UpdateTrade(mdb::Trade* record) override;
	virtual void SelectTrade(std::list<mdb::Trade*>& records) override;
	virtual void TruncateTrade() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::Trade*>& records);
	
	virtual void CreateSEBroker() override;
	virtual void DropSEBroker() override;
	virtual void InsertSEBroker(mdb::SEBroker* record) override;
	virtual void BatchInsertSEBroker(std::list<mdb::SEBroker*>* records) override;
	virtual void DeleteSEBroker(mdb::SEBroker* record) override;
	virtual void UpdateSEBroker(mdb::SEBroker* record) override;
	virtual void SelectSEBroker(std::list<mdb::SEBroker*>& records) override;
	virtual void TruncateSEBroker() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::SEBroker*>& records);
	
	virtual void CreateSEInstrument() override;
	virtual void DropSEInstrument() override;
	virtual void InsertSEInstrument(mdb::SEInstrument* record) override;
	virtual void BatchInsertSEInstrument(std::list<mdb::SEInstrument*>* records) override;
	virtual void DeleteSEInstrument(mdb::SEInstrument* record) override;
	virtual void DeleteSEInstrumentByExchangeIDIndex(mdb::SEInstrument* record) override;
	virtual void UpdateSEInstrument(mdb::SEInstrument* record) override;
	virtual void SelectSEInstrument(std::list<mdb::SEInstrument*>& records) override;
	virtual void TruncateSEInstrument() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::SEInstrument*>& records);
	
	virtual void CreateSEOrder() override;
	virtual void DropSEOrder() override;
	virtual void InsertSEOrder(mdb::SEOrder* record) override;
	virtual void BatchInsertSEOrder(std::list<mdb::SEOrder*>* records) override;
	virtual void DeleteSEOrder(mdb::SEOrder* record) override;
	virtual void DeleteSEOrderByAccountIDIndex(mdb::SEOrder* record) override;
	virtual void UpdateSEOrder(mdb::SEOrder* record) override;
	virtual void SelectSEOrder(std::list<mdb::SEOrder*>& records) override;
	virtual void TruncateSEOrder() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::SEOrder*>& records);
	
	virtual void CreateSETrade() override;
	virtual void DropSETrade() override;
	virtual void InsertSETrade(mdb::SETrade* record) override;
	virtual void BatchInsertSETrade(std::list<mdb::SETrade*>* records) override;
	virtual void DeleteSETrade(mdb::SETrade* record) override;
	virtual void DeleteSETradeByAccountIDIndex(mdb::SETrade* record) override;
	virtual void UpdateSETrade(mdb::SETrade* record) override;
	virtual void SelectSETrade(std::list<mdb::SETrade*>& records) override;
	virtual void TruncateSETrade() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::SETrade*>& records);
	
	virtual void CreateSEBrokerLoginSession() override;
	virtual void DropSEBrokerLoginSession() override;
	virtual void InsertSEBrokerLoginSession(mdb::SEBrokerLoginSession* record) override;
	virtual void BatchInsertSEBrokerLoginSession(std::list<mdb::SEBrokerLoginSession*>* records) override;
	virtual void DeleteSEBrokerLoginSession(mdb::SEBrokerLoginSession* record) override;
	virtual void DeleteSEBrokerLoginSessionByBrokerIDIndex(mdb::SEBrokerLoginSession* record) override;
	virtual void UpdateSEBrokerLoginSession(mdb::SEBrokerLoginSession* record) override;
	virtual void SelectSEBrokerLoginSession(std::list<mdb::SEBrokerLoginSession*>& records) override;
	virtual void TruncateSEBrokerLoginSession() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::SEBrokerLoginSession*>& records);
	
	virtual void CreateDepthMarketData() override;
	virtual void DropDepthMarketData() override;
	virtual void InsertDepthMarketData(mdb::DepthMarketData* record) override;
	virtual void BatchInsertDepthMarketData(std::list<mdb::DepthMarketData*>* records) override;
	virtual void DeleteDepthMarketData(mdb::DepthMarketData* record) override;
	virtual void UpdateDepthMarketData(mdb::DepthMarketData* record) override;
	virtual void SelectDepthMarketData(std::list<mdb::DepthMarketData*>& records) override;
	virtual void TruncateDepthMarketData() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::DepthMarketData*>& records);
	
	virtual void CreateBarMarketData() override;
	virtual void DropBarMarketData() override;
	virtual void InsertBarMarketData(mdb::BarMarketData* record) override;
	virtual void BatchInsertBarMarketData(std::list<mdb::BarMarketData*>* records) override;
	virtual void DeleteBarMarketData(mdb::BarMarketData* record) override;
	virtual void UpdateBarMarketData(mdb::BarMarketData* record) override;
	virtual void SelectBarMarketData(std::list<mdb::BarMarketData*>& records) override;
	virtual void TruncateBarMarketData() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::BarMarketData*>& records);
	
	virtual void CreateMdSubscribe() override;
	virtual void DropMdSubscribe() override;
	virtual void InsertMdSubscribe(mdb::MdSubscribe* record) override;
	virtual void BatchInsertMdSubscribe(std::list<mdb::MdSubscribe*>* records) override;
	virtual void DeleteMdSubscribe(mdb::MdSubscribe* record) override;
	virtual void UpdateMdSubscribe(mdb::MdSubscribe* record) override;
	virtual void SelectMdSubscribe(std::list<mdb::MdSubscribe*>& records) override;
	virtual void TruncateMdSubscribe() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::MdSubscribe*>& records);
	
	virtual void CreateMdUser() override;
	virtual void DropMdUser() override;
	virtual void InsertMdUser(mdb::MdUser* record) override;
	virtual void BatchInsertMdUser(std::list<mdb::MdUser*>* records) override;
	virtual void DeleteMdUser(mdb::MdUser* record) override;
	virtual void UpdateMdUser(mdb::MdUser* record) override;
	virtual void SelectMdUser(std::list<mdb::MdUser*>& records) override;
	virtual void TruncateMdUser() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::MdUser*>& records);
	
	virtual void CreateMdUserLoginSession() override;
	virtual void DropMdUserLoginSession() override;
	virtual void InsertMdUserLoginSession(mdb::MdUserLoginSession* record) override;
	virtual void BatchInsertMdUserLoginSession(std::list<mdb::MdUserLoginSession*>* records) override;
	virtual void DeleteMdUserLoginSession(mdb::MdUserLoginSession* record) override;
	virtual void DeleteMdUserLoginSessionByMdUserIDIndex(mdb::MdUserLoginSession* record) override;
	virtual void UpdateMdUserLoginSession(mdb::MdUserLoginSession* record) override;
	virtual void SelectMdUserLoginSession(std::list<mdb::MdUserLoginSession*>& records) override;
	virtual void TruncateMdUserLoginSession() override;
	static void ParseRecord(duckdb_result& result, std::list<mdb::MdUserLoginSession*>& records);
	

private:
	bool AppendForTradingDayRecord(duckdb_appender appender, mdb::TradingDay* record);
	void SetStatementForTradingDayRecord(duckdb_prepared_statement statement, mdb::TradingDay* record);
	void SetStatementForTradingDayRecordUpdate(duckdb_prepared_statement statement, mdb::TradingDay* record);
	void SetStatementForTradingDayPrimaryKey(duckdb_prepared_statement statement, mdb::TradingDay* record);
	bool AppendForExchangeRecord(duckdb_appender appender, mdb::Exchange* record);
	void SetStatementForExchangeRecord(duckdb_prepared_statement statement, mdb::Exchange* record);
	void SetStatementForExchangeRecordUpdate(duckdb_prepared_statement statement, mdb::Exchange* record);
	void SetStatementForExchangePrimaryKey(duckdb_prepared_statement statement, mdb::Exchange* record);
	bool AppendForProductRecord(duckdb_appender appender, mdb::Product* record);
	void SetStatementForProductRecord(duckdb_prepared_statement statement, mdb::Product* record);
	void SetStatementForProductRecordUpdate(duckdb_prepared_statement statement, mdb::Product* record);
	void SetStatementForProductPrimaryKey(duckdb_prepared_statement statement, mdb::Product* record);
	bool AppendForHotInstrumentRecord(duckdb_appender appender, mdb::HotInstrument* record);
	void SetStatementForHotInstrumentRecord(duckdb_prepared_statement statement, mdb::HotInstrument* record);
	void SetStatementForHotInstrumentRecordUpdate(duckdb_prepared_statement statement, mdb::HotInstrument* record);
	void SetStatementForHotInstrumentPrimaryKey(duckdb_prepared_statement statement, mdb::HotInstrument* record);
	void SetStatementForHotInstrumentIndexTradingDay(duckdb_prepared_statement statement, mdb::HotInstrument* record);
	bool AppendForInstrumentRecord(duckdb_appender appender, mdb::Instrument* record);
	void SetStatementForInstrumentRecord(duckdb_prepared_statement statement, mdb::Instrument* record);
	void SetStatementForInstrumentRecordUpdate(duckdb_prepared_statement statement, mdb::Instrument* record);
	void SetStatementForInstrumentPrimaryKey(duckdb_prepared_statement statement, mdb::Instrument* record);
	bool AppendForPrimaryAccountRecord(duckdb_appender appender, mdb::PrimaryAccount* record);
	void SetStatementForPrimaryAccountRecord(duckdb_prepared_statement statement, mdb::PrimaryAccount* record);
	void SetStatementForPrimaryAccountRecordUpdate(duckdb_prepared_statement statement, mdb::PrimaryAccount* record);
	void SetStatementForPrimaryAccountPrimaryKey(duckdb_prepared_statement statement, mdb::PrimaryAccount* record);
	void SetStatementForPrimaryAccountIndexOfferID(duckdb_prepared_statement statement, mdb::PrimaryAccount* record);
	bool AppendForAccountRecord(duckdb_appender appender, mdb::Account* record);
	void SetStatementForAccountRecord(duckdb_prepared_statement statement, mdb::Account* record);
	void SetStatementForAccountRecordUpdate(duckdb_prepared_statement statement, mdb::Account* record);
	void SetStatementForAccountPrimaryKey(duckdb_prepared_statement statement, mdb::Account* record);
	bool AppendForCapitalRecord(duckdb_appender appender, mdb::Capital* record);
	void SetStatementForCapitalRecord(duckdb_prepared_statement statement, mdb::Capital* record);
	void SetStatementForCapitalRecordUpdate(duckdb_prepared_statement statement, mdb::Capital* record);
	void SetStatementForCapitalPrimaryKey(duckdb_prepared_statement statement, mdb::Capital* record);
	void SetStatementForCapitalIndexTradingDay(duckdb_prepared_statement statement, mdb::Capital* record);
	bool AppendForPositionRecord(duckdb_appender appender, mdb::Position* record);
	void SetStatementForPositionRecord(duckdb_prepared_statement statement, mdb::Position* record);
	void SetStatementForPositionRecordUpdate(duckdb_prepared_statement statement, mdb::Position* record);
	void SetStatementForPositionPrimaryKey(duckdb_prepared_statement statement, mdb::Position* record);
	void SetStatementForPositionIndexAccount(duckdb_prepared_statement statement, mdb::Position* record);
	void SetStatementForPositionIndexTradingDay(duckdb_prepared_statement statement, mdb::Position* record);
	bool AppendForPositionDetailRecord(duckdb_appender appender, mdb::PositionDetail* record);
	void SetStatementForPositionDetailRecord(duckdb_prepared_statement statement, mdb::PositionDetail* record);
	void SetStatementForPositionDetailRecordUpdate(duckdb_prepared_statement statement, mdb::PositionDetail* record);
	void SetStatementForPositionDetailPrimaryKey(duckdb_prepared_statement statement, mdb::PositionDetail* record);
	void SetStatementForPositionDetailIndexTradeMatch(duckdb_prepared_statement statement, mdb::PositionDetail* record);
	void SetStatementForPositionDetailIndexTradingDay(duckdb_prepared_statement statement, mdb::PositionDetail* record);
	bool AppendForOrderRecord(duckdb_appender appender, mdb::Order* record);
	void SetStatementForOrderRecord(duckdb_prepared_statement statement, mdb::Order* record);
	void SetStatementForOrderRecordUpdate(duckdb_prepared_statement statement, mdb::Order* record);
	void SetStatementForOrderPrimaryKey(duckdb_prepared_statement statement, mdb::Order* record);
	bool AppendForTradeRecord(duckdb_appender appender, mdb::Trade* record);
	void SetStatementForTradeRecord(duckdb_prepared_statement statement, mdb::Trade* record);
	void SetStatementForTradeRecordUpdate(duckdb_prepared_statement statement, mdb::Trade* record);
	void SetStatementForTradePrimaryKey(duckdb_prepared_statement statement, mdb::Trade* record);
	bool AppendForSEBrokerRecord(duckdb_appender appender, mdb::SEBroker* record);
	void SetStatementForSEBrokerRecord(duckdb_prepared_statement statement, mdb::SEBroker* record);
	void SetStatementForSEBrokerRecordUpdate(duckdb_prepared_statement statement, mdb::SEBroker* record);
	void SetStatementForSEBrokerPrimaryKey(duckdb_prepared_statement statement, mdb::SEBroker* record);
	bool AppendForSEInstrumentRecord(duckdb_appender appender, mdb::SEInstrument* record);
	void SetStatementForSEInstrumentRecord(duckdb_prepared_statement statement, mdb::SEInstrument* record);
	void SetStatementForSEInstrumentRecordUpdate(duckdb_prepared_statement statement, mdb::SEInstrument* record);
	void SetStatementForSEInstrumentPrimaryKey(duckdb_prepared_statement statement, mdb::SEInstrument* record);
	void SetStatementForSEInstrumentIndexExchangeID(duckdb_prepared_statement statement, mdb::SEInstrument* record);
	bool AppendForSEOrderRecord(duckdb_appender appender, mdb::SEOrder* record);
	void SetStatementForSEOrderRecord(duckdb_prepared_statement statement, mdb::SEOrder* record);
	void SetStatementForSEOrderRecordUpdate(duckdb_prepared_statement statement, mdb::SEOrder* record);
	void SetStatementForSEOrderPrimaryKey(duckdb_prepared_statement statement, mdb::SEOrder* record);
	void SetStatementForSEOrderIndexAccountID(duckdb_prepared_statement statement, mdb::SEOrder* record);
	bool AppendForSETradeRecord(duckdb_appender appender, mdb::SETrade* record);
	void SetStatementForSETradeRecord(duckdb_prepared_statement statement, mdb::SETrade* record);
	void SetStatementForSETradeRecordUpdate(duckdb_prepared_statement statement, mdb::SETrade* record);
	void SetStatementForSETradePrimaryKey(duckdb_prepared_statement statement, mdb::SETrade* record);
	void SetStatementForSETradeIndexAccountID(duckdb_prepared_statement statement, mdb::SETrade* record);
	bool AppendForSEBrokerLoginSessionRecord(duckdb_appender appender, mdb::SEBrokerLoginSession* record);
	void SetStatementForSEBrokerLoginSessionRecord(duckdb_prepared_statement statement, mdb::SEBrokerLoginSession* record);
	void SetStatementForSEBrokerLoginSessionRecordUpdate(duckdb_prepared_statement statement, mdb::SEBrokerLoginSession* record);
	void SetStatementForSEBrokerLoginSessionPrimaryKey(duckdb_prepared_statement statement, mdb::SEBrokerLoginSession* record);
	void SetStatementForSEBrokerLoginSessionIndexBrokerID(duckdb_prepared_statement statement, mdb::SEBrokerLoginSession* record);
	bool AppendForDepthMarketDataRecord(duckdb_appender appender, mdb::DepthMarketData* record);
	void SetStatementForDepthMarketDataRecord(duckdb_prepared_statement statement, mdb::DepthMarketData* record);
	void SetStatementForDepthMarketDataRecordUpdate(duckdb_prepared_statement statement, mdb::DepthMarketData* record);
	void SetStatementForDepthMarketDataPrimaryKey(duckdb_prepared_statement statement, mdb::DepthMarketData* record);
	bool AppendForBarMarketDataRecord(duckdb_appender appender, mdb::BarMarketData* record);
	void SetStatementForBarMarketDataRecord(duckdb_prepared_statement statement, mdb::BarMarketData* record);
	void SetStatementForBarMarketDataRecordUpdate(duckdb_prepared_statement statement, mdb::BarMarketData* record);
	void SetStatementForBarMarketDataPrimaryKey(duckdb_prepared_statement statement, mdb::BarMarketData* record);
	bool AppendForMdSubscribeRecord(duckdb_appender appender, mdb::MdSubscribe* record);
	void SetStatementForMdSubscribeRecord(duckdb_prepared_statement statement, mdb::MdSubscribe* record);
	void SetStatementForMdSubscribeRecordUpdate(duckdb_prepared_statement statement, mdb::MdSubscribe* record);
	void SetStatementForMdSubscribePrimaryKey(duckdb_prepared_statement statement, mdb::MdSubscribe* record);
	bool AppendForMdUserRecord(duckdb_appender appender, mdb::MdUser* record);
	void SetStatementForMdUserRecord(duckdb_prepared_statement statement, mdb::MdUser* record);
	void SetStatementForMdUserRecordUpdate(duckdb_prepared_statement statement, mdb::MdUser* record);
	void SetStatementForMdUserPrimaryKey(duckdb_prepared_statement statement, mdb::MdUser* record);
	bool AppendForMdUserLoginSessionRecord(duckdb_appender appender, mdb::MdUserLoginSession* record);
	void SetStatementForMdUserLoginSessionRecord(duckdb_prepared_statement statement, mdb::MdUserLoginSession* record);
	void SetStatementForMdUserLoginSessionRecordUpdate(duckdb_prepared_statement statement, mdb::MdUserLoginSession* record);
	void SetStatementForMdUserLoginSessionPrimaryKey(duckdb_prepared_statement statement, mdb::MdUserLoginSession* record);
	void SetStatementForMdUserLoginSessionIndexMdUserID(duckdb_prepared_statement statement, mdb::MdUserLoginSession* record);


private:
	std::string m_DBName;
	duckdb_database m_DB;
	duckdb_connection m_Connection;
	char* m_SqlBuff;

	duckdb_prepared_statement m_TradingDayDeleteStatement;
	duckdb_prepared_statement m_TradingDayUpdateStatement;
	duckdb_prepared_statement m_TradingDaySelectStatement;
	duckdb_prepared_statement m_TradingDayTruncateStatement;
	duckdb_prepared_statement m_ExchangeDeleteStatement;
	duckdb_prepared_statement m_ExchangeUpdateStatement;
	duckdb_prepared_statement m_ExchangeSelectStatement;
	duckdb_prepared_statement m_ExchangeTruncateStatement;
	duckdb_prepared_statement m_ProductDeleteStatement;
	duckdb_prepared_statement m_ProductUpdateStatement;
	duckdb_prepared_statement m_ProductSelectStatement;
	duckdb_prepared_statement m_ProductTruncateStatement;
	duckdb_prepared_statement m_HotInstrumentDeleteStatement;
	duckdb_prepared_statement m_HotInstrumentDeleteByTradingDayIndexStatement;
	duckdb_prepared_statement m_HotInstrumentUpdateStatement;
	duckdb_prepared_statement m_HotInstrumentSelectStatement;
	duckdb_prepared_statement m_HotInstrumentTruncateStatement;
	duckdb_prepared_statement m_InstrumentDeleteStatement;
	duckdb_prepared_statement m_InstrumentUpdateStatement;
	duckdb_prepared_statement m_InstrumentSelectStatement;
	duckdb_prepared_statement m_InstrumentTruncateStatement;
	duckdb_prepared_statement m_PrimaryAccountDeleteStatement;
	duckdb_prepared_statement m_PrimaryAccountDeleteByOfferIDIndexStatement;
	duckdb_prepared_statement m_PrimaryAccountUpdateStatement;
	duckdb_prepared_statement m_PrimaryAccountSelectStatement;
	duckdb_prepared_statement m_PrimaryAccountTruncateStatement;
	duckdb_prepared_statement m_AccountDeleteStatement;
	duckdb_prepared_statement m_AccountUpdateStatement;
	duckdb_prepared_statement m_AccountSelectStatement;
	duckdb_prepared_statement m_AccountTruncateStatement;
	duckdb_prepared_statement m_CapitalDeleteStatement;
	duckdb_prepared_statement m_CapitalDeleteByTradingDayIndexStatement;
	duckdb_prepared_statement m_CapitalUpdateStatement;
	duckdb_prepared_statement m_CapitalSelectStatement;
	duckdb_prepared_statement m_CapitalTruncateStatement;
	duckdb_prepared_statement m_PositionDeleteStatement;
	duckdb_prepared_statement m_PositionDeleteByAccountIndexStatement;
	duckdb_prepared_statement m_PositionDeleteByTradingDayIndexStatement;
	duckdb_prepared_statement m_PositionUpdateStatement;
	duckdb_prepared_statement m_PositionSelectStatement;
	duckdb_prepared_statement m_PositionTruncateStatement;
	duckdb_prepared_statement m_PositionDetailDeleteStatement;
	duckdb_prepared_statement m_PositionDetailDeleteByTradeMatchIndexStatement;
	duckdb_prepared_statement m_PositionDetailDeleteByTradingDayIndexStatement;
	duckdb_prepared_statement m_PositionDetailUpdateStatement;
	duckdb_prepared_statement m_PositionDetailSelectStatement;
	duckdb_prepared_statement m_PositionDetailTruncateStatement;
	duckdb_prepared_statement m_OrderDeleteStatement;
	duckdb_prepared_statement m_OrderUpdateStatement;
	duckdb_prepared_statement m_OrderSelectStatement;
	duckdb_prepared_statement m_OrderTruncateStatement;
	duckdb_prepared_statement m_TradeDeleteStatement;
	duckdb_prepared_statement m_TradeUpdateStatement;
	duckdb_prepared_statement m_TradeSelectStatement;
	duckdb_prepared_statement m_TradeTruncateStatement;
	duckdb_prepared_statement m_SEBrokerDeleteStatement;
	duckdb_prepared_statement m_SEBrokerUpdateStatement;
	duckdb_prepared_statement m_SEBrokerSelectStatement;
	duckdb_prepared_statement m_SEBrokerTruncateStatement;
	duckdb_prepared_statement m_SEInstrumentDeleteStatement;
	duckdb_prepared_statement m_SEInstrumentDeleteByExchangeIDIndexStatement;
	duckdb_prepared_statement m_SEInstrumentUpdateStatement;
	duckdb_prepared_statement m_SEInstrumentSelectStatement;
	duckdb_prepared_statement m_SEInstrumentTruncateStatement;
	duckdb_prepared_statement m_SEOrderDeleteStatement;
	duckdb_prepared_statement m_SEOrderDeleteByAccountIDIndexStatement;
	duckdb_prepared_statement m_SEOrderUpdateStatement;
	duckdb_prepared_statement m_SEOrderSelectStatement;
	duckdb_prepared_statement m_SEOrderTruncateStatement;
	duckdb_prepared_statement m_SETradeDeleteStatement;
	duckdb_prepared_statement m_SETradeDeleteByAccountIDIndexStatement;
	duckdb_prepared_statement m_SETradeUpdateStatement;
	duckdb_prepared_statement m_SETradeSelectStatement;
	duckdb_prepared_statement m_SETradeTruncateStatement;
	duckdb_prepared_statement m_SEBrokerLoginSessionDeleteStatement;
	duckdb_prepared_statement m_SEBrokerLoginSessionDeleteByBrokerIDIndexStatement;
	duckdb_prepared_statement m_SEBrokerLoginSessionUpdateStatement;
	duckdb_prepared_statement m_SEBrokerLoginSessionSelectStatement;
	duckdb_prepared_statement m_SEBrokerLoginSessionTruncateStatement;
	duckdb_prepared_statement m_DepthMarketDataDeleteStatement;
	duckdb_prepared_statement m_DepthMarketDataUpdateStatement;
	duckdb_prepared_statement m_DepthMarketDataSelectStatement;
	duckdb_prepared_statement m_DepthMarketDataTruncateStatement;
	duckdb_prepared_statement m_BarMarketDataDeleteStatement;
	duckdb_prepared_statement m_BarMarketDataUpdateStatement;
	duckdb_prepared_statement m_BarMarketDataSelectStatement;
	duckdb_prepared_statement m_BarMarketDataTruncateStatement;
	duckdb_prepared_statement m_MdSubscribeDeleteStatement;
	duckdb_prepared_statement m_MdSubscribeUpdateStatement;
	duckdb_prepared_statement m_MdSubscribeSelectStatement;
	duckdb_prepared_statement m_MdSubscribeTruncateStatement;
	duckdb_prepared_statement m_MdUserDeleteStatement;
	duckdb_prepared_statement m_MdUserUpdateStatement;
	duckdb_prepared_statement m_MdUserSelectStatement;
	duckdb_prepared_statement m_MdUserTruncateStatement;
	duckdb_prepared_statement m_MdUserLoginSessionDeleteStatement;
	duckdb_prepared_statement m_MdUserLoginSessionDeleteByMdUserIDIndexStatement;
	duckdb_prepared_statement m_MdUserLoginSessionUpdateStatement;
	duckdb_prepared_statement m_MdUserLoginSessionSelectStatement;
	duckdb_prepared_statement m_MdUserLoginSessionTruncateStatement;
};
