#pragma once

constexpr const char* CreateMysqlDBTradingDayTableSqlString = "CREATE TABLE IF NOT EXISTS t_TradingDay(PK char(32), CurrTradingDay char(9), PreTradingDay char(9), PRIMARY KEY(PK)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBTradingDayTableSqlString = "Truncate Table t_TradingDay;";

constexpr const char* CreateMysqlDBExchangeTableSqlString = "CREATE TABLE IF NOT EXISTS t_Exchange(ExchangeID char(8), ExchangeName char(64), PRIMARY KEY(ExchangeID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBExchangeTableSqlString = "Truncate Table t_Exchange;";

constexpr const char* CreateMysqlDBProductTableSqlString = "CREATE TABLE IF NOT EXISTS t_Product(ExchangeID char(8), ProductID char(32), ProductName char(32), SecurityType int, VolumeMultiple int, PriceTick double, MaxMarketOrderVolume bigint, MinMarketOrderVolume bigint, MaxLimitOrderVolume bigint, MinLimitOrderVolume bigint, SessionName char(32), PRIMARY KEY(ExchangeID, ProductID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBProductTableSqlString = "Truncate Table t_Product;";

constexpr const char* CreateMysqlDBInstrumentTableSqlString = "CREATE TABLE IF NOT EXISTS t_Instrument(TradingDay char(9), ExchangeID char(8), InstrumentID char(32), ExchangeInstID char(32), InstrumentName char(64), ProductID char(32), SecurityType int, SecurityDetailType int, VolumeMultiple int, PriceTick double, MaxMarketOrderVolume bigint, MinMarketOrderVolume bigint, MaxLimitOrderVolume bigint, MinLimitOrderVolume bigint, SessionName char(32), PRIMARY KEY(ExchangeID, InstrumentID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBInstrumentTableSqlString = "Truncate Table t_Instrument;";

constexpr const char* CreateMysqlDBPrimaryAccountTableSqlString = "CREATE TABLE IF NOT EXISTS t_PrimaryAccount(TradingDay char(9), PrimaryAccountID char(32), PrimaryAccountName char(64), AccountClass int, BrokerPassword char(64), OfferID int, IsAllowLogin bool, IsSimulateAccount bool, LoginStatus int, InitStatus int, INDEX OfferID(OfferID), PRIMARY KEY(PrimaryAccountID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBPrimaryAccountTableSqlString = "Truncate Table t_PrimaryAccount;";

constexpr const char* CreateMysqlDBAccountTableSqlString = "CREATE TABLE IF NOT EXISTS t_Account(TradingDay char(9), AccountID char(32), AccountName char(64), AccountType int, AccountStatus int, Password char(64), TradeGroupID int, RiskGroupID int, CommissionGroupID int, PRIMARY KEY(AccountID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBAccountTableSqlString = "Truncate Table t_Account;";

constexpr const char* CreateMysqlDBCapitalTableSqlString = "CREATE TABLE IF NOT EXISTS t_Capital(TradingDay char(9), AccountID char(32), AccountType int, Asset double, PreAsset double, CashAsset double, PreCashAsset double, Available double, CashIn double, CashOut double, Margin double, Commission double, StampTax double, TransferFee double, FrozenCash double, FrozenMargin double, FrozenCommission double, FrozenStampTax double, FrozenTransferFee double, MarketValue double, TotalProfit double, TodayProfit double, Deposit double, Withdraw double, PRIMARY KEY(AccountID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBCapitalTableSqlString = "Truncate Table t_Capital;";

constexpr const char* CreateMysqlDBPositionTableSqlString = "CREATE TABLE IF NOT EXISTS t_Position(TradingDay char(9), AccountID char(32), AccountType int, ExchangeID char(8), InstrumentID char(32), SecurityType int, PosiDirection int, TotalPosition bigint, PositionFrozen bigint, TodayPosition bigint, CashIn double, CashOut double, Margin double, Commission double, StampTax double, TransferFee double, FrozenCash double, FrozenMargin double, FrozenCommission double, FrozenStampTax double, FrozenTransferFee double, MarketValue double, VolumeMultiple int, CloseProfit double, CloseProfitFloat double, PositionProfit double, PositionProfitFloat double, LastPrice double, PrePrice double, INDEX Account(TradingDay, AccountID), PRIMARY KEY(TradingDay, AccountID, ExchangeID, InstrumentID, PosiDirection)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBPositionTableSqlString = "Truncate Table t_Position;";

constexpr const char* CreateMysqlDBOrderTableSqlString = "CREATE TABLE IF NOT EXISTS t_Order(TradingDay char(9), AccountID char(32), PrimaryAccountID char(32), AccountType int, ExchangeID char(8), InstrumentID char(32), SecurityType int, OrderID int, OrderSysID char(64), Direction int, OffsetFlag int, OrderPriceType int, Price double, Volume bigint, VolumeTotal bigint, VolumeTraded bigint, VolumeMultiple int, OrderStatus int, OrderDate char(9), OrderTime char(9), CancelDate char(9), CancelTime char(9), SessionID bigint, ClientOrderID int, RequestID int, OfferID int, TradeGroupID int, RiskGroupID int, CommissionGroupID int, FrozenCash double, FrozenMargin double, FrozenCommission double, FrozenStampTax double, FrozenTransferFee double, RebuildMark bool, IsForceClose bool, PRIMARY KEY(TradingDay, AccountID, ExchangeID, InstrumentID, OrderID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBOrderTableSqlString = "Truncate Table t_Order;";

constexpr const char* CreateMysqlDBTradeTableSqlString = "CREATE TABLE IF NOT EXISTS t_Trade(TradingDay char(9), AccountID char(32), PrimaryAccountID char(32), AccountType int, ExchangeID char(8), InstrumentID char(32), SecurityType int, OrderID int, OrderSysID char(64), TradeID char(64), Direction int, OffsetFlag int, Price double, Volume bigint, VolumeMultiple int, TradeAmount double, Commission double, StampTax double, TransferFee double, TradeDate char(9), TradeTime char(9), PRIMARY KEY(TradingDay, ExchangeID, TradeID, Direction)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBTradeTableSqlString = "Truncate Table t_Trade;";

constexpr const char* CreateMysqlDBDepthMarketDataTableSqlString = "CREATE TABLE IF NOT EXISTS t_DepthMarketData(TradingDay char(9), ExchangeID char(8), InstrumentID char(32), LastPrice double, PreSettlementPrice double, PreClosePrice double, PreOpenInterest bigint, OpenPrice double, HighestPrice double, LowestPrice double, ClosePrice double, CurrVolume bigint, Volume bigint, CurrTurnover double, Turnover double, OpenInterest bigint, SettlementPrice double, UpperLimitPrice double, LowerLimitPrice double, AveragePrice double, UpdateTs bigint, AskPrice1 double, AskPrice2 double, AskPrice3 double, AskPrice4 double, AskPrice5 double, AskPrice6 double, AskPrice7 double, AskPrice8 double, AskPrice9 double, AskPrice10 double, AskVolume1 bigint, AskVolume2 bigint, AskVolume3 bigint, AskVolume4 bigint, AskVolume5 bigint, AskVolume6 bigint, AskVolume7 bigint, AskVolume8 bigint, AskVolume9 bigint, AskVolume10 bigint, BidPrice1 double, BidPrice2 double, BidPrice3 double, BidPrice4 double, BidPrice5 double, BidPrice6 double, BidPrice7 double, BidPrice8 double, BidPrice9 double, BidPrice10 double, BidVolume1 bigint, BidVolume2 bigint, BidVolume3 bigint, BidVolume4 bigint, BidVolume5 bigint, BidVolume6 bigint, BidVolume7 bigint, BidVolume8 bigint, BidVolume9 bigint, BidVolume10 bigint, PRIMARY KEY(TradingDay, ExchangeID, InstrumentID)) ENGINE=MyISAM DEFAULT COLLATE='utf8mb4_bin';";
constexpr const char* TruncateMysqlDBDepthMarketDataTableSqlString = "Truncate Table t_DepthMarketData;";

