DROP TABLE IF EXISTS t_TradingDay;
DROP TABLE IF EXISTS t_Exchange;
DROP TABLE IF EXISTS t_Product;
DROP INDEX HotInstrumentTradingDay;
DROP TABLE IF EXISTS t_HotInstrument;
DROP TABLE IF EXISTS t_Instrument;
DROP INDEX PrimaryAccountOfferID;
DROP TABLE IF EXISTS t_PrimaryAccount;
DROP TABLE IF EXISTS t_Account;
DROP INDEX CapitalTradingDay;
DROP TABLE IF EXISTS t_Capital;
DROP INDEX PositionAccount;
DROP INDEX PositionTradingDay;
DROP TABLE IF EXISTS t_Position;
DROP INDEX PositionDetailTradeMatch;
DROP INDEX PositionDetailTradingDay;
DROP TABLE IF EXISTS t_PositionDetail;
DROP TABLE IF EXISTS t_Order;
DROP TABLE IF EXISTS t_Trade;
DROP TABLE IF EXISTS t_SEBroker;
DROP INDEX SEInstrumentExchangeID;
DROP TABLE IF EXISTS t_SEInstrument;
DROP INDEX SEOrderAccountID;
DROP TABLE IF EXISTS t_SEOrder;
DROP INDEX SETradeAccountID;
DROP TABLE IF EXISTS t_SETrade;
DROP INDEX SEBrokerLoginSessionBrokerID;
DROP TABLE IF EXISTS t_SEBrokerLoginSession;
DROP TABLE IF EXISTS t_DepthMarketData;
DROP TABLE IF EXISTS t_BarMarketData;
DROP TABLE IF EXISTS t_MdSubscribe;
DROP TABLE IF EXISTS t_MdUser;
DROP INDEX MdUserLoginSessionMdUserID;
DROP TABLE IF EXISTS t_MdUserLoginSession;
